In [2]:
import torch
import numpy as np

In [26]:
x = torch.arange(6).reshape(2, 3)
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [27]:
x1 = torch.cat((x, x, x), 0)
print(x1)
print(x1.shape)

tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])
torch.Size([6, 3])


In [28]:
x2 = torch.cat((x, x, x), 1)
print(x2)
print(x2.shape)

tensor([[0, 1, 2, 0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5, 3, 4, 5]])
torch.Size([2, 9])


In [33]:
torch.randn_like(x, dtype=torch.float)

tensor([[-0.0968,  0.9048,  1.9466],
        [-1.0629, -0.9585,  1.5765]])

In [34]:
shape = (2,3,)

In [37]:
torch.zeros(shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [38]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [40]:
torch.backends.mps.is_available()

True

In [45]:
tensor = torch.ones(4, 4)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [47]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [48]:
tensor = torch.ones(4, 4)
tensor[1,:] = 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [49]:
tensor = torch.ones(2, 2, 2)
print(tensor)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


In [52]:
tensor = torch.ones(2, 2, 2)
tensor[:,:, 1] = 0
print(tensor)

tensor([[[1., 0.],
         [1., 0.]],

        [[1., 0.],
         [1., 0.]]])


In [53]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [57]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
print(t1.shape)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
torch.Size([4, 12])


In [56]:
t2 = torch.cat([tensor, tensor, tensor], dim=0)
print(t2)
print(t2.shape)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
torch.Size([12, 4])


In [60]:
tensor2 = torch.ones(4, 4) + 1
# 逐个元素相乘结果
print(f"tensor.mul(tensor2): \n {tensor.mul(tensor2)} \n")
# 等价写法:
print(f"tensor * tensor2: \n {tensor * tensor2}")

tensor.mul(tensor2): 
 tensor([[2., 0., 2., 2.],
        [2., 0., 2., 2.],
        [2., 0., 2., 2.],
        [2., 0., 2., 2.]]) 

tensor * tensor2: 
 tensor([[2., 0., 2., 2.],
        [2., 0., 2., 2.],
        [2., 0., 2., 2.],
        [2., 0., 2., 2.]])


In [62]:
print(f"tensor: \n {tensor}")
print(f"tensor.T: \n {tensor.T}")
print(f"tensor.matmul(tensor.T): \n {tensor.matmul(tensor.T)} \n")
# 等价写法:
print(f"tensor @ tensor.T")

tensor: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor.T: 
 tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor.matmul(tensor.T): 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T


In [66]:
t1 = torch.arange(4).reshape(2, 2)
print(t1)
t2 = t1 + 1
print(t2)
print(t1 @ t2)

tensor([[0, 1],
        [2, 3]])
tensor([[1, 2],
        [3, 4]])
tensor([[ 3,  4],
        [11, 16]])


In [67]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [68]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [72]:
n = np.ones(5)
t = torch.from_numpy(n)

In [74]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [70]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [127]:
x = torch.tensor([1, 2, 3])
print(x.size())
x1 = x.expand(2, -1)
print(x1)
x1.size()

torch.Size([3])
tensor([[1, 2, 3],
        [1, 2, 3]])


torch.Size([2, 3])

In [85]:
x = torch.arange(9).view(3, 3)
print(x)
x.size()

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


torch.Size([3, 3])

In [135]:
x1 = x.expand(1, 3, -1)
print(x1)
x1.size()

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]])


torch.Size([1, 3, 3])

In [117]:
x = torch.tensor([1, 2, 3])
print(x.size())
x1 = x.repeat(2, 3)
print(x1)
x1.size()

torch.Size([3])
tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3]])


torch.Size([2, 9])

In [4]:
x = torch.tensor([1, 2, 3])
print(x.size())
x1 = x.repeat(1, 3)
print(x1)
x1.size()

torch.Size([3])
tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3]])


torch.Size([1, 9])

In [148]:
x = torch.arange(1, 8)
print(x)
x1 = x.unfold(-1, 3, 4)
print(x1)
print(x1.size())

tensor([1, 2, 3, 4, 5, 6, 7])
tensor([[1, 2, 3],
        [5, 6, 7]])
torch.Size([2, 3])


In [151]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)
print(x.size())
x1 = x.narrow(0, 0, 2)
print(x1)
print(x1.size())

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.Size([3, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [153]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)
print(x.size())
x1 = x.narrow(1, 1, 1)
print(x1)
print(x1.size())

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.Size([3, 3])
tensor([[2.],
        [5.],
        [8.]])
torch.Size([3, 1])


In [155]:
x = torch.zeros(2, 3, 5)
print(x.size())
x1 = x.permute(2, 0, 1)
print(x1.size())

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


In [156]:
x1.element_size()

4

In [172]:
x=[0,1,2,3,4]
x1 = x[::-1]
print(x1)

[4, 3, 2, 1, 0]


In [173]:
x = torch.zeros(2, 1, 2, 1, 2)
print(x.size())
x1 = torch.squeeze(x, 3)
print(x1.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 1, 2, 2])


In [178]:
x = torch.zeros(2, 3)
print(x.size())
x1 = torch.unsqueeze(x, 1)
print(x1)
print(x1.size())

torch.Size([2, 3])
tensor([[[0., 0., 0.]],

        [[0., 0., 0.]]])
torch.Size([2, 1, 3])


In [9]:
import torch
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence, pack_padded_sequence, pack_sequence, pad_packed_sequence
 
class MyData(Dataset):
  def __init__(self, data):
      self.data = data
  def __len__(self):
      return len(self.data)
  def __getitem__(self, idx):
      length = len(self.data[idx])
      return self.data[idx]
 
def collate_fn(data):
    # data.sort(key=lambda x: len(x), reverse=True)
    seq_len = [s.size(0) for s in data] # 获取数据真实的长度
    data = pad_sequence(data, batch_first=True)
    data = pack_padded_sequence(data, seq_len, batch_first=True)
    return data
 
a = torch.tensor([1, 2, 3, 4]) # sentence 1
b = torch.tensor([5, 6, 7]) # sentence 2
c = torch.tensor([7, 8]) # sentence 3
d = torch.tensor([9]) # sentence 4
 
train_x = [a, b, c, d]
 
data = MyData(train_x)
data_loader = DataLoader(data, batch_size=2, shuffle=True, collate_fn=collate_fn)
 
batch_x = iter(data_loader)
for i in range (2):
 print(next(batch_x))

PackedSequence(data=tensor([5, 7, 6, 8, 7]), batch_sizes=tensor([2, 2, 1]), sorted_indices=None, unsorted_indices=None)
PackedSequence(data=tensor([1, 9, 2, 3, 4]), batch_sizes=tensor([2, 1, 1, 1]), sorted_indices=None, unsorted_indices=None)


In [6]:
batch = [[1, 4, 2], [2, 3]]
batch.sort(key=lambda x: len(x), reverse=False)
print(batch)

[[2, 3], [1, 4, 2]]
