In [1]:
import torch

In [2]:
batch_size = 1
seq_len = 3
input_size = 4
hidden_size = 2

In [3]:
cell = torch.nn.RNNCell(input_size=input_size, hidden_size=hidden_size)

In [4]:
dataset = torch.randn(seq_len, batch_size, input_size)
hidden = torch.zeros(batch_size, hidden_size)

print(dataset.shape)
print(hidden.shape)

torch.Size([3, 1, 4])
torch.Size([1, 2])


In [5]:
for idx, input in enumerate(dataset):
    print("="*20, idx, "="*20)
    print("Input size: ", input.shape)

    hidden  = cell(input, hidden)

    print("Output size: ", hidden.shape)
    print(hidden)

==================== 0 ====================
Input size:  torch.Size([1, 4])
Output size:  torch.Size([1, 2])
tensor([[0.7238, 0.8326]], grad_fn=<TanhBackward0>)
==================== 1 ====================
Input size:  torch.Size([1, 4])
Output size:  torch.Size([1, 2])
tensor([[-0.0059,  0.9283]], grad_fn=<TanhBackward0>)
==================== 2 ====================
Input size:  torch.Size([1, 4])
Output size:  torch.Size([1, 2])
tensor([[-0.6333,  0.9750]], grad_fn=<TanhBackward0>)


In [6]:
batch_size = 6
seq_len = 3
input_size = 4

hidden_size = 5
num_layers = 2

dataset = torch.randn(seq_len, batch_size, input_size)
hidden = torch.zeros(num_layers, batch_size, hidden_size)

print(dataset.shape)
print(hidden.shape)

torch.Size([3, 6, 4])
torch.Size([2, 6, 5])


In [7]:
rnn = torch.nn.RNN(input_size=input_size, hidden_size=hidden_size, num_layers=num_layers)

In [8]:
output, hidden = rnn(dataset, hidden)

print("Output size(All hidden): ", output.shape) # seq, batch, hidden
print("Final Hidden size: ", hidden.shape) # num_layers, batch, hidden

Output size(All hidden):  torch.Size([3, 6, 5])
Final Hidden size:  torch.Size([2, 6, 5])


In [9]:
batch_size = 6
seq_len = 3
input_size = 4

hidden_size = 5
num_layers = 2

dataset = torch.randn(batch_size, seq_len, input_size)
hidden = torch.zeros(num_layers, batch_size, hidden_size)

print('dataset', dataset.shape)
print('hidden', hidden.shape)

rnn = torch.nn.RNN(input_size=input_size, hidden_size=hidden_size, num_layers=num_layers, batch_first=True)

print(dataset.shape)
print(hidden.shape)
output, hidden = rnn(dataset, hidden)

print("Output size(All hidden): ", output.shape) # seq, batch, hidden
print("Final Hidden size: ", hidden.shape) # num_layers, batch, hidden

torch.Size([6, 3, 4])
torch.Size([2, 6, 5])
torch.Size([6, 3, 4])
torch.Size([2, 6, 5])
Output size(All hidden):  torch.Size([6, 3, 5])
Final Hidden size:  torch.Size([2, 6, 5])
